apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-agent-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-agent-app
  template:
    metadata:
      labels:
        app: devops-agent-app
    spec:
      containers:
      - name: devops-agent-app
        image: REPLACEME_IMAGE_TAG
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-agent-service
spec:
  type: LoadBalancer 
  selector:
    app: devops-agent-app
  ports:
  - port: 80
    targetPort: 5000